use_frameworks!

platform :ios, '11.0'

target 'notifyvisitors_Example' do
  pod 'notifyvisitors'

  target 'notifyvisitors_Tests' do
    inherit! :search_paths
  end
end

target 'NotificationServiceExtension' do
  pod 'notifyvisitors'
end
